### ISSUE TITLE
Bug: amount of the supply item for the hospitals

### ISSUE THREAD

**Issue by yaluye** [pengcc/against-covid19#21]
Should exclude empty fields which means it's not a requested item. That should not be counted towards the total number. 
Copy should be in English: "+X more items".

**Comment by pengcc** [comment]
@yaluye 
- The text has been fixed. 
- The other issue about the empty fields needs more consideration since there is no number in the data, if we exclude the empty fields, that means no items will show up on the whole page.

**Comment by yaluye** [comment]
@pengcc thanks! 
Yeah, if it's empty in the sheet, it means it's not a requested item in that entry, so it shouldn't be displayed in that entry. 
Also, another note - can we show "Unknown" or "-" for the option of "don't know the number"?

**Comment by yaluye** [comment]
@pengcc feel free to suggest how we can make this less confusing or less level of effort in dev, e.g. we can update the field option of "don't know the number", and add some indicator for "not requested" in the field.

**Comment by pengcc** [comment]
@yaluye 
1. don't need to touch the data, "don't know the number" will be treated as an uncertain quantity "-" 
2. and only display the items with a certain quantity or  an uncertain quantity "-" 

Changes have been deployed, take a look, close this ticket if everything is ok.

**Comment by yaluye** [comment]
Looks good!
